[build]
  command = "npm run build"
  publish = "dist"
  functions = "./src/functions"
  NODE_ENV = "14.18.0"

[dev]
  publish = "./dist"
  command = "npm run watch"

[context.production]
  environment = { NODE_VERSION = "14.18.0", NODE_ENV = "production" }

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/blog/:slug"
  to = "/:slug"
  status = 200
