[build]
  command = "npm run build"
  publish = "dist"
  functions = "./src/functions"
  NODE_ENV = "14.18.0"

[dev]
  command = "npm run start"

[context.production]
  environment = { NODE_VERSION = "14.18.0", NODE_ENV = "production" }
